#ifndef VERSION_H
#define VERSION_H

// This file is auto-generated by the CI build pipeline.
// Local builds use the default version below.
// The GitHub Actions workflow replaces this with the actual tag version.
#define FIRMWARE_VERSION "dev"

// GitHub repository for OTA update checks
#define OTA_GITHUB_API_URL "https://api.github.com/repos/joojoooo/SeleniumChess/releases/latest"

#endif // VERSION_H
